/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-25 14:07:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.studio2.www_studiodragon_net.front.kr.about;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from www.studiodragon.net/front/kr/about/contact by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 22 Aug 2019 10:24:59 GMT -->\r\n");
      out.write("<!-- Added by HTTrack --><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" /><!-- /Added by HTTrack -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\" />\r\n");
      out.write("\t<meta property=\"og:title\" content=\"STUDIO DRAGON\" />\r\n");
      out.write("\t<meta property=\"og:description\" content=\"스튜디오 드래곤\" />\r\n");
      out.write("\t<meta property=\"og:url\" content=\"../../../index.jsp\" />\r\n");
      out.write("\t<meta property=\"og:image\" content=\"../../../resources/front/kr/images/com/link.jpg\" />\r\n");
      out.write("\t<meta name=\"description\" content=\"아시아의 콘텐츠와 라이프 스타일을 선도하는 Asia No.1 Studio 스튜디오 드래곤에 오시는 길을 안내합니다.\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"스튜디오 드래곤, CJ, CJ E&M, CJ 스튜디오 드래곤, STUDIO DRAGON, 오시는길, 문의, 제작 문의, 투자, 제휴, 리메이크, 광고, 라이선싱, MD\">\r\n");
      out.write("\t<title>Contact Us | 스튜디오 드래곤</title>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../../openapi.map.naver.com/openapi/v3/mapsbcfe.js?ncpClientId=3yrh2oapiw\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../resources/front/kr/css/common.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../resources/front/kr/css/contents.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../resources/front/kr/js/plugin/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../resources/front/kr/js/plugin/jquery.dotdotdot.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../resources/front/kr/js/plugin/skrollr.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../resources/front/kr/js/plugin/velocity.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../resources/front/kr/js/common_ui.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../resources/js/common/common.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\r\n");
      out.write("\t\t(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\r\n");
      out.write("\t\tm=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\r\n");
      out.write("\t\t})(window,document,'script','../../../../www.google-analytics.com/analytics.js','ga');\r\n");
      out.write("\t\tga('create', 'UA-97845877-1', 'auto');\r\n");
      out.write("\t\tga('send', 'pageview');\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"skipNav\">\r\n");
      out.write("\t<a href=\"#container\"><span>본문 바로가기</span></a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\t<!-- S : header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- S : header -->\r\n");
      out.write("\t<div id=\"header\" class=\"transit overflowHidden\">\r\n");
      out.write("\t<!-- 하위메뉴 펼침 .hopen 추가 /scroll height:453px / 1280이하일때 .hmob -->\r\n");
      out.write("\t\t<h1><a href=\"../main/main.jsp\" class=\"transit\">STUDIO DRAGON</a></h1>\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" class=\"ico-menu\"></a>\r\n");
      out.write("\t\t<div class=\"mobile-wrap\">\r\n");
      out.write("\t\t\t<div id=\"gnb\" class=\"\"><!--gng 오버했을때 class open 추가 -->\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"on\"><a href=\"company.jsp\" class=\"menu1 transit\">ABOUT</a><!-- tablet에서 부터 선택됐을때 li에 class on 넣어줌 -->\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li  ><a href=\"company.jsp\">ABOUT US</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li  ><a href=\"history.jsp\">COMPANY HISTORY</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li  ><a href=\"partner.jsp\">PARTNERS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"on\"><a href=\"contact.jsp\">CONTACT US</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li ><a href=\"../works/portfolio.jsp\" class=\"menu1 transit\">WORKS</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../works/portfolio.jsp\">SHOWS</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li ><a href=\"../career/talent.jsp\" class=\"menu1 transit\">CAREERS</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../career/talent.jsp\">RECRUITMENT</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../career/recruit.jsp\">FEATURED JOBS</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li ><a href=\"../pr/notice.jsp\" class=\"menu1 transit\">NEWSROOM</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../pr/notice.jsp\">NOTICE</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../pr/news.jsp\">PRESS RELEASES</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../ir/viewer.jsp\" class=\"menu1 transit\">시청자 의견</a>\r\n");
      out.write("\t\t\t\t\t<!-- <li ><a href=\"../ir/activities.jsp\" class=\"menu1 transit\">IR</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/activities.jsp\">IR ACTIVITIES &amp; MATERIALS</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../ir/disclosure.jsp\">DISCLOSURE</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/notice.jsp\">PUBLIC NOTICE</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../ir/stock.jsp\">STOCK INFORMATION</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/finance.jsp\">FINANCIAL INFORMATION</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/governance.jsp\">CORPORATE GOVERNANCE</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"language transit\">\r\n");
      out.write("\t\t\t\t<li class=\"on\"><a href=\"../main/main.jsp\" class=\"transit\">KOR</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"../../en/main/main.jsp\" class=\"transit\">ENG</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" class=\"close\">닫기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dim\"></div>\r\n");
      out.write("\t<!-- E: header -->\r\n");
      out.write("\t<!-- E: header -->\r\n");
      out.write("\t<div class=\"visual-area about\">\r\n");
      out.write("\t\t<div class=\"visual-area-in\">\r\n");
      out.write("\t\t\t<h2>CONTACT US</h2>\r\n");
      out.write("\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t<p><a href=\"../main/main.jsp\"><img src=\"../../../resources/front/kr/images/com/ico_home.png\" alt=\"HOME\" /></a><span>ABOUT</span><span>CONTACT US</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"current-location\">\r\n");
      out.write("\t\t\t\t<p><a href=\"../main/main.jsp\"><img src=\"../../../resources/front/kr/images/com/ico_home_side.png\" alt=\"HOME\" /></a><span>ABOUT</span><span>CONTACT US</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"frame\"><span class=\"line\"></span><span class=\"edge\"></span></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- S : container -->\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div class=\"content contact\">\r\n");
      out.write("\t\t\t<div class=\"sub-tit-txt\">\r\n");
      out.write("\t\t\t\t<p>스튜디오 드래곤은 다양한 웰메이드 드라마를 기획,<br />제작하여 국내 컨텐츠 개발에 기여하고 있습니다.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"mapArea\" id=\"mapArea\">\r\n");
      out.write("\t\t\t\t<!--<p class=\"position\"><a href=\"#\"><img src=\"../common/images/about/img_position.png\" alt=\"Studio Dragon\" /></a></p>-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"contactusWrap\">\r\n");
      out.write("\t\t\t\t<dl class=\"addressInfo list01\">\r\n");
      out.write("\t\t\t\t\t<dt>찾아오시는 길</dt>\r\n");
      out.write("\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t<p>서울특별시 마포구 매봉산로 75, 17층 (상암동, DDMC)</p>\r\n");
      out.write("\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t<ul class=\"contactMail\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"list02\">\r\n");
      out.write("\t\t\t\t\t\t\t<dt>제작/투자/제휴/<br />리메이크 문의</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><a href=\"mailto:business.sd@cj.net\">business.sd@cj.net</a></dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"list03\">\r\n");
      out.write("\t\t\t\t\t\t\t<dt>광고/라이선싱/<br />MD 문의</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><a href=\"mailto:ad.sd@cj.net\">ad.sd@cj.net</a></dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- E : container -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tvar pos = new naver.maps.LatLng(37.5784652, 126.8929289);\r\n");
      out.write("\r\n");
      out.write("\tvar mapOptions = {\r\n");
      out.write("\t\tcenter: pos,\r\n");
      out.write("\t\tzoom : 11,\r\n");
      out.write("\t\tmapTypeControl:true,\r\n");
      out.write("\t\tzoomControl: true,\r\n");
      out.write("\t\tlogoControl:false,\r\n");
      out.write("\t\tzoomControlOptions: {\r\n");
      out.write("\t\t\tstyle: naver.maps.ZoomControlStyle.DROPDOWN,\r\n");
      out.write("\t\t\tposition: naver.maps.Position.LEFT_TOP\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar map = new naver.maps.Map('mapArea', mapOptions);\r\n");
      out.write("\r\n");
      out.write("\tvar pcIcon = {\r\n");
      out.write("\t\t\turl: '/resources/front/kr/images/about/img_position.png',\r\n");
      out.write("\t\t\tsize: new naver.maps.Size(186, 101),\r\n");
      out.write("\t\t\tscaledSize: new naver.maps.Size(186, 101),\r\n");
      out.write("\t\t\torigin: new naver.maps.Point(0, 0),\r\n");
      out.write("\t\t\tanchor: new naver.maps.Point(107, 101)\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\tvar mobileIcon = {\r\n");
      out.write("\t\t\turl: '/resources/front/kr/images/about/img_position.png',\r\n");
      out.write("\t\t\tsize: new naver.maps.Size(93, 50),\r\n");
      out.write("\t\t\tscaledSize: new naver.maps.Size(93, 50),\r\n");
      out.write("\t\t\torigin: new naver.maps.Point(0, 0),\r\n");
      out.write("\t\t\tanchor: new naver.maps.Point(53, 50)\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\tvar marker = new naver.maps.Marker({\r\n");
      out.write("\t\tposition: pos,\r\n");
      out.write("\t\tmap:map,\r\n");
      out.write("\t\tanimation:naver.maps.Animation.DROP\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tsetIcon();\r\n");
      out.write("\tmap.panBy(new naver.maps.Point(0, -25)); // 하단으로 25 픽셀 이동\r\n");
      out.write("\r\n");
      out.write("\tvar wmode;\r\n");
      out.write("\r\n");
      out.write("\twindow.onresize = function(e){\r\n");
      out.write("\t\tvar currentMode;\r\n");
      out.write("\r\n");
      out.write("\t\tif( window.innerWidth > 768 ){\r\n");
      out.write("\t\t\tcurrentMode = \"pc\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tcurrentMode = \"mobile\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif( wmode != currentMode){\r\n");
      out.write("\t\t\tsetIcon();\r\n");
      out.write("\t\t\twmode = currentMode;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction setIcon(){\r\n");
      out.write("\t\tif( window.innerWidth > 768 ){\r\n");
      out.write("\t\t\tmarker.setIcon(pcIcon);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tmarker.setIcon(mobileIcon);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- S : footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- S : footer -->\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-in\">\r\n");
      out.write("\t\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t\t<div class=\"family\"><!-- class on 추가 -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"sel\">Family Site<span class=\"arr\">Family Site 더보기</span></a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"http://www.cj.net/\" target=\"_blank\">CJ 그룹</a></li><!-- 선택된 값에 class active 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.cjenm.com/\" target=\"_blank\">CJ ENM(E&M)</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://tvn.tving.com/\" target=\"_blank\">tvN</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://ocn.tving.com/\" target=\"_blank\">OCN</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.culturedepot.kr/\" target=\"_blank\">문화창고</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://jspictures.tv/\" target=\"_blank\">JS Pictures</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"footer-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../etc/lawNotice.jsp\">법적고지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:void(0)\" onclick=\"ShowModalPopup(this,'popEmail');\">이메일 무단수집 거부</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../etc/ethics.jsp\">윤리경영</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"contact.jsp\">CONTACT US</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../etc/sitemap.jsp\">사이트맵</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-txt\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-logo\"><img src=\"../../../resources/front/kr/images/com/footer_logo.png\" alt=\"studio dragon\" /></div>\r\n");
      out.write("\t\t\t\t<div class=\"txt\">\r\n");
      out.write("\t\t\t\t\t<p>서울특별시 마포구 매봉산로 75, 17층 스튜디오 드래곤 주식회사</p>\r\n");
      out.write("\t\t\t\t\t<span>FAX : +82 2-2146-0988</span>\r\n");
      out.write("\t\t\t\t\t<span>사업자등록번호 : 747-81-00388</span>\r\n");
      out.write("\t\t\t\t\t<span>대표자 : 최진희</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"copyright\">©2017 <strong>STUDIO DRAGON Corp.</strong> All Rights Reserved.</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- E : footer -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 이메일 무단수집 거부 팝업 -->\r\n");
      out.write("<div id=\"popEmail\" class=\"LayerPop\">\r\n");
      out.write("\t<dl class=\"popCnts\">\r\n");
      out.write("\t\t<dt>이메일 무단수집 거부</dt>\r\n");
      out.write("\t\t<dd class=\"emailNoti\">\r\n");
      out.write("\t\t\t<p>본 웹사이트에 게시된 이메일 주소가 전자우편 수집 프로그램이나 그 밖의 기술적 장치를 이용하여 무단으로 수집되는 것을 거부하며, 이를 위반시 정보통신망법에 의해 형사 처벌 됨을 유념하시기 바랍니다.</p>\r\n");
      out.write("\t\t\t<p class=\"date\">게시일 : 2017. 06. 01</p>\r\n");
      out.write("\t\t</dd>\r\n");
      out.write("\t</dl>\r\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"btnClose\" onclick=\"HideModalPopup('popEmail');\"><img src=\"../../../resources/front/kr/images/com/btn_pop_close.png\" alt=\"팝업 닫기\" /></a>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //이메일 무단수집 거부 팝업 -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from www.studiodragon.net/front/kr/about/contact by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 22 Aug 2019 10:24:59 GMT -->\r\n");
      out.write("</html>\r\n");
      out.write("<!-- E : footer -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
