/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-26 05:18:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.studio2.www_studiodragon_net.front.kr.ir;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\"><head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("\t<meta name=\"description\" content=\"아시아의 콘텐츠와 라이프 스타일을 선도하는 Asia No.1 Studio 스튜디오 드래곤의 IR 정보, 공고 페이지입니다.\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"스튜디오 드래곤, CJ, CJ E&amp;M, CJ 스튜디오 드래곤, STUDIO DRAGON, IR, 공고, 전자공고\">\r\n");
      out.write("\t<title>Public Notice | 스튜디오 드래곤</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/common.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/contents.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugin/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugin/jquery.dotdotdot.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugin/skrollr.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugin/velocity.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/common_ui.js\"></script>\r\n");
      out.write("<!-- Iframe resizer -->\r\n");
      out.write("     <!-- <script type=\"text/javascript\" src=\"http://totalstock.irplus.co.kr/StockUtil/iframe_rz/iframeResizer.contentWindow.min.js\"></script> -->\r\n");
      out.write("     <!-- <script type=\"text/javascript\" src=\"../../../totalstock.irplus.co.kr/StockUtil/iframe_rz/jquery.iframeResizer.min.js\"></script> -->\t\r\n");
      out.write("     <!--<script type=\"text/javascript\" src=\"http://wcs.naver.net/wcslog.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"> if(!wcs_add) var wcs_add = {}; wcs_add[\"wa\"] = \"1d20e427ddf2bf\"; wcs_do(); </script>-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"skipNav\">\r\n");
      out.write("\t<a href=\"#container\"><span>본문 바로가기</span></a>\r\n");
      out.write("</div>\r\n");
      out.write("\t<!-- S : header -->\r\n");
      out.write("\t<!-- E: header -->\r\n");
      out.write("\t<!-- S : container -->\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<table class=\"type10\">\r\n");
      out.write("\t\t    <thead>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t        <th scope=\"cols\">타이틀</th>\r\n");
      out.write("\t\t        <th scope=\"cols\">내용</th>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t    </thead>\r\n");
      out.write("\t\t    <tbody>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <th scope=\"row\">항목명</th>\r\n");
      out.write("\t\t\t        <td>내용이 들어갑니다.</td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <th scope=\"row\">항목명</th>\r\n");
      out.write("\t\t\t        <td>내용이 들어갑니다.</td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <th scope=\"row\">항목명</th>\r\n");
      out.write("\t\t\t        <td>내용이 들어갑니다.</td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t        <th scope=\"row\">항목명</th>\r\n");
      out.write("\t\t\t        <td>내용이 들어갑니다.</td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t    </tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div class=\"section-pagination\" aria-label=\"Pagination\">\r\n");
      out.write("\t\t\t\t<h4 class=\"blind\">목록 페이징</h4>\r\n");
      out.write("\t\t\t\t<div class=\"paging_wrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"num\"><span>1</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<!-- E : container -->\r\n");
      out.write("\t<!-- S : footer -->\r\n");
      out.write("\t<!-- E : footer -->\r\n");
      out.write("<!-- 이메일 무단수집 거부 팝업 -->\r\n");
      out.write("<!-- //이메일 무단수집 거부 팝업 -->\r\n");
      out.write("\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
