/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-26 14:35:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.User.etc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ethics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<!-- Mirrored from www.studiodragon.net/front/kr/etc/ethics by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 22 Aug 2019 10:25:05 GMT -->\n");
      out.write("<!-- Added by HTTrack --><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" /><!-- /Added by HTTrack -->\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no\" />\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\" />\n");
      out.write("\t<meta property=\"og:title\" content=\"STUDIO DRAGON\" />\n");
      out.write("\t<meta property=\"og:description\" content=\"스튜디오 드래곤\" />\n");
      out.write("\t<meta property=\"og:url\" content=\"../main/main/index.jsp\" />\n");
      out.write("\t<meta property=\"og:image\" content=\"../../../img/User/com/link.jpg\" />\n");
      out.write("\t<meta name=\"description\" content=\"아시아의 콘텐츠와 라이프 스타일을 선도하는 Asia No.1 Studio 스튜디오 드래곤의 윤리경영을 알려드립니다.\">\n");
      out.write("\t<meta name=\"keywords\" content=\"스튜디오 드래곤, CJ, CJ ENM, CJ 스튜디오드래곤, STUDIO DRAGON, 윤리경영\">\n");
      out.write("\t<title>윤리경영 | 스튜디오 드래곤</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../css/User/common.css\" />\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../css/User/contents.css\" />\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/plugin/jquery-1.12.4.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/plugin/jquery.dotdotdot.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/plugin/skrollr.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/plugin/velocity.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/common_ui.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/common.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\t(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n");
      out.write("\t\t(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n");
      out.write("\t\tm=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n");
      out.write("\t\t})(window,document,'script','../../../js/User/analytics.js','ga');\n");
      out.write("\t\tga('create', 'UA-97845877-1', 'auto');\n");
      out.write("\t\tga('send', 'pageview');\n");
      out.write("\t</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"skipNav\">\n");
      out.write("\t<a href=\"#container\"><span>본문 바로가기</span></a>\n");
      out.write("</div>\n");
      out.write("<div id=\"wrap\">\n");
      out.write("\t<!-- S : header -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- S : header -->\n");
      out.write("\t<div id=\"header\" class=\"transit overflowHidden\">\n");
      out.write("\t<!-- 하위메뉴 펼침 .hopen 추가 /scroll height:453px / 1280이하일때 .hmob -->\n");
      out.write("\t\t<h1><a href=\"../main/main.jsp\" class=\"transit\">STUDIO DRAGON</a></h1>\n");
      out.write("\t\t<a href=\"javascript:void(0);\" class=\"ico-menu\"></a>\n");
      out.write("\t\t<div class=\"mobile-wrap\">\n");
      out.write("\t\t\t<div id=\"gnb\" class=\"\"><!--gng 오버했을때 class open 추가 -->\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li ><a href=\"../about/company.jsp\" class=\"menu1 transit\">ABOUT</a><!-- tablet에서 부터 선택됐을때 li에 class on 넣어줌 -->\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li  ><a href=\"../about/company.jsp\">ABOUT US</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li  ><a href=\"../about/history.jsp\">COMPANY HISTORY</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li  ><a href=\"../about/partner.jsp\">PARTNERS</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../about/contact.jsp\">CONTACT US</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li ><a href=\"../works/portfolio.jsp\" class=\"menu1 transit\">WORKS</a>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../works/portfolio.jsp\">SHOWS</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li ><a href=\"../career/talent.jsp\" class=\"menu1 transit\">CAREERS</a>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../career/talent.jsp\">RECRUITMENT</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../career/recruit.jsp\">FEATURED JOBS</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li ><a href=\"../newsroom/news.jsp\" class=\"menu1 transit\">NEWSROOM</a>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../pr/notice.jsp\">NOTICE</a></li> -->\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../newsroom/news.jsp\">PRESS RELEASES</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li><a href=\"../viewercomments/viewer.jsp\" class=\"menu1 transit\">시청자 의견</a>\n");
      out.write("                        <ul>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/activities.jsp\">IR ACTIVITIES &amp; MATERIALS</a></li>\n");
      out.write("                        </ul>    \n");
      out.write("\t\t\t\t\t<!-- <li ><a href=\"../ir/activities.jsp\" class=\"menu1 transit\">IR</a>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/activities.jsp\">IR ACTIVITIES &amp; MATERIALS</a></li> -->\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../ir/disclosure.jsp\">DISCLOSURE</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/notice.jsp\">PUBLIC NOTICE</a></li> -->\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../ir/stock.jsp\">STOCK INFORMATION</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/finance.jsp\">FINANCIAL INFORMATION</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/governance.jsp\">CORPORATE GOVERNANCE</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</li> -->\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<ul class=\"language transit\">\n");
      out.write("\t\t\t\t<li class=\"on\"><a href=\"../main/main.jsp\" class=\"transit\">KOR</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"../../Admin/login.html\" class=\"transit\">login</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<a href=\"javascript:void(0);\" class=\"close\">닫기</a>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"dim\"></div>\n");
      out.write("\t<!-- E: header -->\n");
      out.write("\t<!-- E: header -->\n");
      out.write("\t<!-- S : container -->\n");
      out.write("\t<div id=\"container\">\n");
      out.write("\t\t<div class=\"content etc\">\n");
      out.write("\t\t\t<h2 class=\"etcTitle\">윤리경영</h2>\n");
      out.write("\t\t\t<p>안녕하세요. CJ ENM(스튜디오드래곤) 사이버감사실입니다.<br/>스튜디오드래곤 임직원은 건강, 즐거움, 편리를 창조하는 제일 좋은 회사라는 Vision과 함께 고객만족, 주주가치 극대화, 임직원 만족을 추구하고 있으며, 공정하고 투명한 기업경영을 위해 최선을 다하고 있습니다.</p>\n");
      out.write("\t\t\t<ul class=\"ethicsCntArea\">\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<h3 class=\"etcSubTit\">1. 사이버감사실 안내</h3>\n");
      out.write("\t\t\t\t\t<p>스튜디오드래곤 임직원들의 불공정한 업무처리나 직위를 이용한 부당한 요구행위 및 비리에 대한 제보를 받으며 비공개 방식으로 처리됩니다.<br/>귀하의 소중한 한마디가 투명경영의 초석이 됩니다.</p>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<h3 class=\"etcSubTit\">2. 신고대상</h3>\n");
      out.write("\t\t\t\t\t<ul class=\"notifyList\">\n");
      out.write("\t\t\t\t\t\t<li>1) 임직원의 공금횡령, 유용 및 금품수뢰 사실</li>\n");
      out.write("\t\t\t\t\t\t<li>2) 임직원의 부당한 업무처리</li>\n");
      out.write("\t\t\t\t\t\t<li>3) 거래와 관련된 제반 불이익 상황</li>\n");
      out.write("\t\t\t\t\t\t<li>4) 비상장 거래업체에 대한 부당 지분참여 행위</li>\n");
      out.write("\t\t\t\t\t\t<li>5) 임직원의 업무 외적인 사업행위 및 이중취업 행위</li>\n");
      out.write("\t\t\t\t\t\t<li>6) 성희롱에 따른 풍기문란 행위 등</li>\n");
      out.write("\t\t\t\t\t\t<li>7) 청탁금지법 위반행위</li>\n");
      out.write("\t\t\t\t\t\t<li>8) 기타 불합리 행위</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t<h3 class=\"etcSubTit\">3. 신고처</h3>\n");
      out.write("\t\t\t\t\t<p>스튜디오드래곤의 제보처리는 CJ ENM 감사팀에서 통합 처리됩니다.</p>\n");
      out.write("\t\t\t\t\t<ul class=\"notifyList02\">\n");
      out.write("\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t1) 실명신고\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"notifyWay\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><strong>- 이메일</strong> <span>cjauditor@cj.net</span></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><strong>- 주소</strong> <span>서울시 마포구 상암산로 66, CJ ENM 감사팀</span></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li>2) 익명신고 (<a href=\"https://www.redwhistle.org/report/reportNew.asp?organ=7569\" target=\"_blank\" class=\"linkNewPage\">바로가기</a>)</li>\n");
      out.write("\t\t\t\t\t\t<li>3) CJ그룹 사이버감사실 (<a href=\"https://www.cj.net/footer/cyber2.asp\" target=\"_blank\" class=\"linkNewPage\">바로가기</a>)</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- E : container -->\n");
      out.write("\t<script>\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\t\t$(\"#header\").addClass(\"white\");\n");
      out.write("\t});\n");
      out.write("\t</script>\n");
      out.write("\t<!-- S : footer -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- S : footer -->\n");
      out.write("\t<div id=\"footer\">\n");
      out.write("\t\t<div class=\"footer-in\">\n");
      out.write("\t\t\t<div class=\"footer-top\">\n");
      out.write("\t\t\t\t<div class=\"family\"><!-- class on 추가 -->\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"sel\">Family Site<span class=\"arr\">Family Site 더보기</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"http://www.cj.net/\" target=\"_blank\">CJ 그룹</a></li><!-- 선택된 값에 class active 추가 -->\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.cjenm.com/\" target=\"_blank\">CJ ENM(E&M)</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://tvn.tving.com/\" target=\"_blank\">tvN</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://ocn.tving.com/\" target=\"_blank\">OCN</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.culturedepot.kr/\" target=\"_blank\">문화창고</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://jspictures.tv/\" target=\"_blank\">JS Pictures</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<ul class=\"footer-menu\">\n");
      out.write("\t\t\t\t\t<li><a href=\"lawNotice.jsp\">법적고지</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:void(0)\" onclick=\"ShowModalPopup(this,'popEmail');\">이메일 무단수집 거부</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"ethics.jsp\">윤리경영</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"../about/contact.jsp\">CONTACT US</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"sitemap.jsp\">사이트맵</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"footer-txt\">\n");
      out.write("\t\t\t\t<div class=\"footer-logo\"><img src=\"../../../img/User/com/footer_logo.png\" alt=\"studio dragon\" /></div>\n");
      out.write("\t\t\t\t<div class=\"txt\">\n");
      out.write("\t\t\t\t\t<p>서울특별시 마포구 매봉산로 75, 17층 스튜디오 드래곤 주식회사</p>\n");
      out.write("\t\t\t\t\t<span>FAX : +82 2-2146-0988</span>\n");
      out.write("\t\t\t\t\t<span>사업자등록번호 : 747-81-00388</span>\n");
      out.write("\t\t\t\t\t<span>대표자 : 최진희</span>\n");
      out.write("\t\t\t\t\t<span class=\"copyright\">©2017 <strong>STUDIO DRAGON Corp.</strong> All Rights Reserved.</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- E : footer -->\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 이메일 무단수집 거부 팝업 -->\n");
      out.write("<div id=\"popEmail\" class=\"LayerPop\">\n");
      out.write("\t<dl class=\"popCnts\">\n");
      out.write("\t\t<dt>이메일 무단수집 거부</dt>\n");
      out.write("\t\t<dd class=\"emailNoti\">\n");
      out.write("\t\t\t<p>본 웹사이트에 게시된 이메일 주소가 전자우편 수집 프로그램이나 그 밖의 기술적 장치를 이용하여 무단으로 수집되는 것을 거부하며, 이를 위반시 정보통신망법에 의해 형사 처벌 됨을 유념하시기 바랍니다.</p>\n");
      out.write("\t\t\t<p class=\"date\">게시일 : 2017. 06. 01</p>\n");
      out.write("\t\t</dd>\n");
      out.write("\t</dl>\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"btnClose\" onclick=\"HideModalPopup('popEmail');\"><img src=\"../../../img/User/com/btn_pop_close.png\" alt=\"팝업 닫기\" /></a>\n");
      out.write("</div>\n");
      out.write("<!-- //이메일 무단수집 거부 팝업 -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<!-- Mirrored from www.studiodragon.net/front/kr/etc/ethics by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 22 Aug 2019 10:25:05 GMT -->\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
