/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-08-29 12:05:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.User.about;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class company_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<!-- Mirrored from www.studiodragon.net/front/kr/about/company by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 22 Aug 2019 10:24:57 GMT -->\r\n");
      out.write("<!-- Added by HTTrack --><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" /><!-- /Added by HTTrack -->\r\n");
      out.write("<head>\r\n");
      out.write(" \r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta name=\"format-detection\" content=\"telephone=no\" />\r\n");
      out.write("\t<meta property=\"og:title\" content=\"STUDIO DRAGON\" />\r\n");
      out.write("\t<meta property=\"og:description\" content=\"스튜디오 드래곤\" />\r\n");
      out.write("\t<meta property=\"og:url\" content=\"../main/main.jsp\">\r\n");
      out.write("\t<meta property=\"og:image\" content=\"../../../img/User/com/link.jpg\" />\r\n");
      out.write("\t<meta name=\"description\" content=\"아시아의 콘텐츠와 라이프 스타일을 선도하는 Asia No.1 Studio 스튜디오 드래곤의 회사소개입니다.\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"스튜디오 드래곤, CJ, CJ E&M, CJ 스튜디오 드래곤, STUDIO DRAGON, 회사소개, 사업소개, 사업분야, 드라마, 글로벌 드라마, 콘텐츠, 글로벌 콘텐츠, 웰메이드 드라마, 국내 드라마, 드라마 제작, 드라마 배급, 드라마 기획, 제작자, 드라마 한류, 시청자, 콘텐츠 산업\">\r\n");
      out.write("\t<title>About Us | 스튜디오 드래곤</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../css/User/common.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../css/User/contents.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/plugin/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/plugin/jquery.dotdotdot.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/plugin/skrollr.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/plugin/velocity.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/common_ui.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../../../js/User/common.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\r\n");
      out.write("\t\t(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\r\n");
      out.write("\t\tm=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\r\n");
      out.write("\t\t})(window,document,'script','../../../js/User/analytics.js','ga');\r\n");
      out.write("\t\tga('create', 'UA-97845877-1', 'auto');\r\n");
      out.write("\t\tga('send', 'pageview');\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"skipNav\">\r\n");
      out.write("\t<a href=\"#container\"><span>본문 바로가기</span></a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\t<!-- S : header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- S : header -->\r\n");
      out.write("\t<div id=\"header\" class=\"transit overflowHidden\">\r\n");
      out.write("\t<!-- 하위메뉴 펼침 .hopen 추가 /scroll height:453px / 1280이하일때 .hmob -->\r\n");
      out.write("\t\t<h1><a href=\"../main/main.jsp\" class=\"transit\">STUDIO DRAGON</a></h1>\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" class=\"ico-menu\"></a>\r\n");
      out.write("\t\t<div class=\"mobile-wrap\">\r\n");
      out.write("\t\t\t<div id=\"gnb\" class=\"\"><!--gng 오버했을때 class open 추가 -->\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"on\"><a href=\"company.jsp\" class=\"menu1 transit\">ABOUT</a><!-- tablet에서 부터 선택됐을때 li에 class on 넣어줌 -->\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"on\" ><a href=\"company.jsp\">ABOUT US</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li  ><a href=\"history.jsp\">COMPANY HISTORY</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li  ><a href=\"partner.jsp\">PARTNERS</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"contact.jsp\">CONTACT US</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li ><a href=\"../works/portfolio.jsp\" class=\"menu1 transit\">WORKS</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../works/portfolio.jsp\">SHOWS</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li ><a href=\"../career/talent.jsp\" class=\"menu1 transit\">CAREERS</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../career/talent.jsp\">RECRUITMENT</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../career/recruit.jsp\">FEATURED JOBS</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li ><a href=\"../newsroom/Releases.do\" class=\"menu1 transit\">NEWSROOM</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../pr/notice.jsp\">NOTICE</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../newsroom/Releases.do\">PRESS RELEASES</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../viewercomments/ViewerListAction.do\" class=\"menu1 transit\">시청자 의견</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../viewercomments/ViewerListAction.do\">시청자 의견</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<!-- <li ><a href=\"../ir/activities.jsp\" class=\"menu1 transit\">IR</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/activities.jsp\">IR ACTIVITIES &amp; MATERIALS</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../ir/disclosure.jsp\">DISCLOSURE</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/notice.jsp\">PUBLIC NOTICE</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li ><a href=\"../ir/stock.jsp\">STOCK INFORMATION</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/finance.jsp\">FINANCIAL INFORMATION</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"../ir/governance.jsp\">CORPORATE GOVERNANCE</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"language transit\">\r\n");
      out.write("\t\t\t\t<li class=\"on\"><a href=\"../main/main.jsp\" class=\"transit\">KOR</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"../../Admin/login.jsp\" class=\"transit\">login</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"javascript:void(0);\" class=\"close\">닫기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"dim\"></div>\r\n");
      out.write("\t<!-- E: header -->\r\n");
      out.write("\t<!-- E: header -->\r\n");
      out.write("\t<div class=\"visual-area about\">\r\n");
      out.write("\t\t<div class=\"visual-area-in\">\r\n");
      out.write("\t\t\t<h2>ABOUT US</h2>\r\n");
      out.write("\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t<p><a href=\"../main/main.jsp\"><img src=\"../../../img/User/com/ico_home.png\" alt=\"HOME\" /></a><span>ABOUT</span><span>ABOUT US</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"current-location\">\r\n");
      out.write("\t\t\t\t<p><a href=\"../main/main.jsp\"><img src=\"../../../img/User/com/ico_home_side.png\" alt=\"HOME\" /></a><span>ABOUT</span><span>ABOUT US</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"frame\"><span class=\"line\"></span><span class=\"edge\"></span></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- S : container -->\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div class=\"content full all\">\r\n");
      out.write("\t\t\t<div class=\"companyWrap full\">\r\n");
      out.write("\t\t\t\t<dl class=\"sub-tit-txt type2\">\r\n");
      out.write("\t\t\t\t\t<dt>스튜디오 드래곤은 ‘웰메이드 드라마’ 제작을 통한<br /> 국내 드라마 콘텐츠의 질적 향상과 더불어, 사업의 전문성을 강화하고<br /> 글로벌 사업을 추진하여 문화적 국가경쟁력 확보에 앞장섭니다.</dt>\r\n");
      out.write("\t\t\t\t\t<dd>케이블, 지상파, 모바일 드라마와 베트남, 중국, 북미 등 글로벌 방영 드라마의 기획,<br /> 제작과 배급을 담당하는 드라마 기획 및 제작 전문 스튜디오입니다.</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"companyWrap full1\">\r\n");
      out.write("\t\t\t\t<div class=\"companyBox\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"company-info\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<span>설립</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>2016.05.03</span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<span>대표</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>최진희</span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<span>자본금</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>140억원 (2017.12)</span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<span>모회사</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span>CJ ENM E&M부문</span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"companyWrap business\">\r\n");
      out.write("\t\t\t\t<div class=\"business-wrap left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"txt-area\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"h3-bul ent\">BUSINESS</h3>\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t<dt>늘 새로운 시도로 시청자들에게<br /> 보는 즐거움을 선사합니다.<br /> 창작자, 제작사들과 상생을 통한<br /> 동반성장을 추구합니다.</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>새롭고 차별화된 소재로 기획, 제작한 웰메이드 드라마를 다양한<br /> 채널에 공급하여 국내 드라마 시장 저변 확대에 기여하고 있습니다.<br /> 스튜디오 자체 제작과 더불어 신인 창작자의 성장을 지원하고, 실력<br /> 있는 기성 제작자들과의 네트워크를 강화하여 더욱 영향력 있는<br /> 조직으로 나아가고 있습니다.\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"img-area\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"right-frame\"><span></span></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img\" data-bottom-top=\"transform:translate3d(0px, 200px, 0px);\" data-top-bottom=\"transform:translate3d(0px, -200px, 0px);\"><img src=\"../../../img/User/about/img_company1.jpg\" alt=\"드라마 제작 환경 사진\" /></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"business-wrap right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"txt-area\">\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t<dt>당사의 우수한 드라마를 해외에<br /> 수출하고, 새로운 시장을 개척하며<br /> 드라마 한류를 선도하고 있습니다. </dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>빠르게 성장 중인 중국, 동남아시아 사업자들과 활발한 교류를 이루고 있으며, 로컬 사업자와의 합작 프로젝트, 제작 컨설팅 등을 통해 현지에서도 고퀄리티의 드라마를 선보이고 있습니다.<br /> 중국, 동남아 외에도 새로운 시장을 개척하며 글로벌 사업을 적극 확대할 계획입니다.</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"img-area\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"left-frame\"><span></span></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"img\" data-bottom-top=\"transform:translate3d(0px, 500px, 0px);\" data-top-bottom=\"transform:translate3d(0px, -500px, 0px);\"><img src=\"../../../img/User/about/img_company2.jpg\" alt=\"제작 드라마 장면 사진\" /></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"companyWrap ceo\">\r\n");
      out.write("\t\t\t\t<span class=\"bg\"></span>\r\n");
      out.write("<!-- \t\t\t\t<span class=\"photo\"><img src=\"/resources/front/kr/images/about/photo1.png\" alt=\"Studio Dragon 대표 최진희 사진\" /></span> -->\r\n");
      out.write("\t\t\t\t<p>국내와 아시아에 안주하지 않고 2020년에는 타임워너, 월트디즈니와<br /> 경쟁할 정도의 세계 ‘톱10’ 미디어 콘텐츠 회사로 도약하겠습니다.</p>\r\n");
      out.write("\t\t\t\t<p>그리고 산업 전체와 구성 사업자와의 동반 성장을 위해, 초과 성과에 대한 분배,<br /> 제작환경 개선, 신인 크리에이터 육성 등을 체계적으로 지원할 계획입니다.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"companyWrap vision\">\r\n");
      out.write("\t\t\t\t<div class=\"companyBox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"vision-txt\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"h3-bul ent\">VISION &<br /> MISSION</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>전세계 시청자에게 다양한 양질의 콘텐츠를 제공하고 기성, 신진 창작자가 좋은 창작물을 낼 수 있도록 지원하며 차별화된 퀄리티의 작품을 시도하여 콘텐츠 발전에 앞장섭니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>업계 리더로써 콘텐츠 산업의 건전한 생태계 조성에 힘쓰고, 관련한 일자리 창출을 실천합니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"vision-imgarea\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<span>아시아의 콘텐츠와 라이프스타일을 선도하는</span><span class=\"point\">ASIA NO.1 STUDIO</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"right-frame\"><span></span></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"signature\">\r\n");
      out.write("\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t<dt>CI 소개</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd class=\"txt\">‘Drama Paragon’ 여의주를 품은 아시아의 龍</dd>\r\n");
      out.write("\t\t\t\t\t\t<dd>아시아의 신화와 전설 상의 영물인 龍은 상상력과 창의력을 바탕으로 세계로<br /> 도약하는 아시아의 기상, 스튜디오 드래곤을 상징합니다.</dd>\r\n");
      out.write("\t\t\t\t\t\t<dd class=\"ci\"><img src=\"../../../img/User/about/company_ci.png\" alt=\"studiodragon\" /></dd>\r\n");
      out.write("\t\t\t\t\t\t<dd class=\"btns\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:void(0);\" onclick=\"fnDownload('StudioDragon_CI.jsp','StudioDragon_CI.jsp');\" class=\"btn icodown\">AI파일 다운로드<span class=\"icon\">파일 내려받기</span></a><a href=\"javascript:void(0);\" onclick=\"fnDownload('StudioDragon_CI-2.jsp','StudioDragon_CI-2.jsp');\" class=\"btn icodown\">JPG파일 다운로드<span class=\"icon\">파일 내려받기</span></a>\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- E : container -->\r\n");
      out.write("\t<form name=\"frmDownload\" id=\"frmDownload\" method=\"POST\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"path\" id=\"path\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"oriName\" id=\"oriName\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"svrName\" id=\"svrName\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"isStatic\" id=\"isStatic\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction fnDownload(svrName, oriName) {\r\n");
      out.write("\t\t\t$(\"#path\").val(\"download/ci/index.jsp\");\r\n");
      out.write("\t\t\t$(\"#isStatic\").val(\"Y\");\r\n");
      out.write("\t\t\t$(\"#svrName\").val(svrName);\r\n");
      out.write("\t\t\t$(\"#oriName\").val(oriName);\r\n");
      out.write("\t\t\t$(\"#frmDownload\").attr(\"action\", \"/common/download\");\r\n");
      out.write("\t\t\t$(\"#frmDownload\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- S : footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- S : footer -->\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t<div class=\"footer-in\">\r\n");
      out.write("\t\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t\t<div class=\"family\"><!-- class on 추가 -->\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"sel\">Family Site<span class=\"arr\">Family Site 더보기</span></a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"http://www.cj.net/\" target=\"_blank\">CJ 그룹</a></li><!-- 선택된 값에 class active 추가 -->\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.cjenm.com/\" target=\"_blank\">CJ ENM(E&M)</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://tvn.tving.com/\" target=\"_blank\">tvN</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://ocn.tving.com/\" target=\"_blank\">OCN</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.culturedepot.kr/\" target=\"_blank\">문화창고</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://jspictures.tv/\" target=\"_blank\">JS Pictures</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"footer-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../etc/lawNotice.jsp\">법적고지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:void(0)\" onclick=\"ShowModalPopup(this,'popEmail');\">이메일 무단수집 거부</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../etc/ethics.jsp\">윤리경영</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"contact.jsp\">CONTACT US</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"../etc/sitemap.jsp\">사이트맵</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-txt\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-logo\"><img src=\"../../../img/User/com/footer_logo.png\" alt=\"studio dragon\" /></div>\r\n");
      out.write("\t\t\t\t<div class=\"txt\">\r\n");
      out.write("\t\t\t\t\t<p>서울특별시 마포구 매봉산로 75, 17층 스튜디오 드래곤 주식회사</p>\r\n");
      out.write("\t\t\t\t\t<span>FAX : +82 2-2146-0988</span>\r\n");
      out.write("\t\t\t\t\t<span>사업자등록번호 : 747-81-00388</span>\r\n");
      out.write("\t\t\t\t\t<span>대표자 : 최진희</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"copyright\">©2017 <strong>STUDIO DRAGON Corp.</strong> All Rights Reserved.</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- E : footer -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 이메일 무단수집 거부 팝업 -->\r\n");
      out.write("<div id=\"popEmail\" class=\"LayerPop\">\r\n");
      out.write("\t<dl class=\"popCnts\">\r\n");
      out.write("\t\t<dt>이메일 무단수집 거부</dt>\r\n");
      out.write("\t\t<dd class=\"emailNoti\">\r\n");
      out.write("\t\t\t<p>본 웹사이트에 게시된 이메일 주소가 전자우편 수집 프로그램이나 그 밖의 기술적 장치를 이용하여 무단으로 수집되는 것을 거부하며, 이를 위반시 정보통신망법에 의해 형사 처벌 됨을 유념하시기 바랍니다.</p>\r\n");
      out.write("\t\t\t<p class=\"date\">게시일 : 2017. 06. 01</p>\r\n");
      out.write("\t\t</dd>\r\n");
      out.write("\t</dl>\r\n");
      out.write("\t<a href=\"javascript:void(0)\" class=\"btnClose\" onclick=\"HideModalPopup('popEmail');\"><img src=\"../../../img/User/com/btn_pop_close.png\" alt=\"팝업 닫기\" /></a>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //이메일 무단수집 거부 팝업 -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from www.studiodragon.net/front/kr/about/company by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 22 Aug 2019 10:24:57 GMT -->\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
